### ISSUE TITLE
Error while running install.

### ISSUE THREAD

**Issue by mwj8410** [zandaqo/iswasmfast#1]
First off, good job on creating a demo of this API. I really enjoyed digging into it, and this project is what spurred that on.

**Node** v8.1
**NPM** v5.3.0
**OS** Mac OSX 10.11.6

I encountered a number of errors while running `npm -install` seems to be related to nodejs/node-addon-api#99. Updating to **Node** version 8.5.0 and got past most of it, but the following remained:
```
/[*path redacted*]/iswasmfast/node_modules/node-addon-api/napi-inl.h:421:24: error: use
      of undeclared identifier 'napi_create_double'
  napi_status status = napi_create_double(env, val, &value);
                       ^
1 error generated.
```

Altering `./lib/fermat.cpp` line 24 to:
```
int a = 2 + rand() % (n-4);
```

Corrected the problem. It built and ran fine.
Repo seems to be blocking from creating branches, or else I would have filed a pull request for this.

Also, please note that more detail in the REDME file on the expected environment would have been helpful.

**Comment by zandaqo** [comment]
Thanks @mwj8410! 
I've increased the requirement for the engine to 8.5 to address the compatibility issue. I cannot reproduce the issue with std::rand(), but I've changed it to rand() anyway as you suggested.

**Comment by mwj8410** [comment]
Perfect!

I pulled, wiped `node_modules`, reinstalled, and re-ran. No issues.

I've not dug into the added documentation yet, but looks good. Thanks again.
